driver:
  name: terraform
  variable_files:
    - terraform.tfvars

provisioner:
  name: terraform

platforms:
 - name: ubuntu

verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      hostnames: public_ip
      user: ubuntu
      hosts_output: public_ip
      key_files:
      - /home/nikolay/AWS_key/aws_key_pair.pem
suites:
  - name: default
