---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
 - name: ubuntu

transport:
  name: ssh
  ssh_key: /home/nikolay/aws_key_pair.pem

verifier:
  name: terraform
  format: doc
  systems:
    - name: default
      backend: local
      hostnames: public_dns
      username: ubuntu

suites:
  - name: default
